baseURL = 'https://lemmack.github.io/'
languageCode = 'en-us'
title = 'Macklem J. Curtis'
theme = [] # We will use local layouts for a custom feel

[params]
  description = "Personal website and blog of Macklem J. Curtis"
  author = "Macklem J. Curtis"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 20
