baseURL = 'https://lemmack.github.io/'
languageCode = 'en-us'
title = 'Macklem Curtis'
theme = 'PaperMod'
enableGitInfo = true

[params]
  description = "Personal website and blog of Macklem Curtis"
  author = "Macklem Curtis"
  toc = true
  ShowToc = true
  defaultTheme = "auto"
  disableSpecial1stPost = true
  ShowAllPagesInArchive = true
  mainSections = ["posts"]
  
  [params.profileMode]
    enabled = true
    title = "Thinking out loud about human health"
    subtitle = "Here lies a collection of my assorted thoughts related to human health. Note that these posts are \"alive\" in the sense that they are meant to be incomplete and to evolve over time through regular updates."

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 20
