baseURL = 'https://lemmack.github.io/'
languageCode = 'en-us'
title = 'Macklem Curtis'
theme = 'PaperMod'
enableGitInfo = true

[params]
  description = "Personal website and blog of Macklem Curtis"
  author = "Macklem Curtis"
  toc = true
  ShowToc = true
  defaultTheme = "light"
  disableSpecial1stPost = true
  ShowAllPagesInArchive = true
  mainSections = ["posts"]
  DateFormat = "Jan 2, 2006"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/MacklemCurtis"

  [[params.socialIcons]]
    name = "microblog"
    url = "https://macklem.micro.blog"

  [params.profileMode]
    enabled = true
    title = "Thinking out loud about human health"
    subtitle = "Here lies a collection of my assorted thoughts and investigations related to human health and the social scaffolding around it."

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "essays"
    name = "Essays"
    url = "/essays/"
    weight = 15
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 20
